import type { NeatConfig } from '@firecms/neat'
import { NeatBackground } from './neat-background'

const config: NeatConfig = {
  colors: [
    {
      color: '#5460F0',
      enabled: true,
    },
    {
      color: '#97A0FF',
      enabled: true,
    },
    {
      color: '#727CFA',
      enabled: true,
    },
    {
      color: '#4150DF',
      enabled: true,
    },
    {
      color: '#2c47f6',
      enabled: false,
    },
    {
      color: '#<n>000000</n>',
      enabled: false,
    },
  ],
  speed: 0.5,
  horizontalPressure: 5,
  verticalPressure: 5,
  waveFrequencyX: 2,
  waveFrequencyY: 3,
  waveAmplitude: 6,
  shadows: 1,
  highlights: 2,
  colorBrightness: 1.35,
  colorSaturation: 3,
  wireframe: false,
  colorBlending: 5,
  backgroundColor: '#FFFFFF',
  backgroundAlpha: 1,
  grainScale: 7,
  grainSparsity: 0.1,
  grainIntensity: 0.15,
  grainSpeed: 0.3,
  resolution: 0.5,
  yOffset: 0,
  yOffsetWaveMultiplier: 1,
  yOffsetColorMultiplier: 4.8,
  yOffsetFlowMultiplier: 5.3,
  flowDistortionA: 3.7,
  flowDistortionB: 0.8,
  flowScale: 1.6,
  flowEase: 0.32,
  flowEnabled: true,
  enableProceduralTexture: false,
  transparentTextureVoid: true,
  textureVoidLikelihood: 0.29,
  textureVoidWidthMin: 120,
  textureVoidWidthMax: 420,
  textureBandDensity: 2.9,
  textureColorBlending: 0.06,
  textureSeed: 536,
  textureEase: 0.93,
  proceduralBackgroundColor: '#<n>775454</n>',
  textureShapeTriangles: 48,
  textureShapeCircles: 15,
  textureShapeBars: 15,
  textureShapeSquiggles: 27,
  domainWarpEnabled: true,
  domainWarpIntensity: 0.05,
  domainWarpScale: 2.4,
  vignetteIntensity: 0.55,
  vignetteRadius: 0.4,
  fresnelEnabled: false,
  fresnelPower: 2.7,
  fresnelIntensity: 1.3,
  fresnelColor: '#F7E7CE',
  iridescenceEnabled: false,
  iridescenceIntensity: 0.5,
  iridescenceSpeed: 1,
  bloomIntensity: 1.8,
  bloomThreshold: 0.75,
  chromaticAberration: 0,
  shapeType: 'ribbon',
  shapeRotationX: -1.99,
  shapeRotationY: -2.49,
  shapeRotationZ: -1.69,
  shapeAutoRotateSpeedX: 0,
  shapeAutoRotateSpeedY: 0,
  sphereRadius: 15,
  torusRadius: 15,
  torusTube: 5,
  cylinderRadius: 10,
  cylinderHeight: 40,
  planeBend: -3,
  planeTwist: 5,
  silhouetteFade: 0.8,
  cylinderFade: 0.08,
  ribbonFade: 0.11,
  flatShading: false,
  cameraLock: false,
  cameraX: 0,
  cameraY: -10.5,
  cameraZ: -0.5,
  cameraRotationX: -0.333,
  cameraRotationY: -0.483,
  cameraRotationZ: 0.41,
  cameraZoom: 1.4,
}

export function LandingBackground() {
  return <NeatBackground config={config} />
}
